[package]
name = "nanos_ui"
version = "0.1.0"
authors = ["yhql"]
edition = "2018"

[dependencies]
nanos_sdk = { git = "https://github.com/waves-enterprise/ledger-nanos-sdk", branch = "fix_unit_tests" } 
